### ISSUE TITLE
Error when running Scraper

### ISSUE THREAD

**Issue by goose2288** [mattheworres/hootdraft-scraper#2]
I get this error when trying to run scraper

`C:\Users---\Downloads\hootdraft-scraper-master\hootdraft-scraper-master>yarn
scrape ncaabb
yarn run v1.22.0
$ node scraper.js ncaabb
internal/modules/cjs/loader.js:984
throw err;
^

Error: Cannot find module 'lodash'
Require stack:

C:\Users---\Downloads\hootdraft-scraper-master\hootdraft-scraper-master\sc
raper.js
←[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981
:15)←[39m
←[90m at Function.Module._load (internal/modules/cjs/loader.js:863:27)←[39m
←[90m at Module.require (internal/modules/cjs/loader.js:1043:19)←[39m
←[90m at require (internal/modules/cjs/helpers.js:77:18)←[39m
at Object.<anonymous> (C:\Users\Maggie\Downloads\hootdraft-scraper-master\ho
otdraft-scraper-master\scraper.js:1:16)
←[90m at Module._compile (internal/modules/cjs/loader.js:1157:30)←[39m
←[90m at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:1
0)←[39m
←[90m at Module.load (internal/modules/cjs/loader.js:1001:32)←[39m
←[90m at Function.Module._load (internal/modules/cjs/loader.js:900:14)←[39m
←[90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:74:12)←[39m {
code: ←[32m'MODULE_NOT_FOUND'←[39m,
requireStack: [
←[32m'C:\Users\---\Downloads\hootdraft-scraper-master\hootdraft-scra
per-master\scraper.js'←[39m
]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.`

Any ideas?  Thanks for any help!

**Comment by goose2288** [comment]
I got it working.  Had to do npm install first then ran scraper.  Thanks for this!!

**Comment by mattheworres** [comment]
That's awesome, glad you were able to figure it out. I was reticent to write a scraper because you're always beholden to whatever source you scrape, so I was *really* afraid that's what happened and I'd have to fix it lol. Happy scraping!
